version: '3.5'
services:
  client:
    image: node:13
    volumes:
      - ./client:/client/
    ports:
      - 4000:3000
    command: npm start
    working_dir: /client/
    stdin_open: true
  server:
    image: node:13
    ports:
      - 2020:8080
    volumes:
      - ./server:/server
    command: npm run dev
    working_dir: /server/